import { AdditionalItem } from './additionalItem.model';
import { Company } from './company.model';
import { Customer } from './customer.model';
import { HireItem } from './hireItem.model';
import { Item } from './item.model';
import { LabourBroker } from './labour-broker.model';
import { LabourItem } from './labourItem.model';

export interface Invoice {
  acceptedBy?: string;
  additionals?: AdditionalItem[];
  attachments?: Item[];
  boards?: Item[];
  broker?: LabourBroker;
  code?: string;
  company?: Company;
  createdBy?: string;
  customer?: Customer;
  date?: any;
  deposit?: number;
  depositTotal?: number;
  depositType?: string;
  discount?: number;
  discountPercentage?: number;
  endDate?: any;
  estimateCode?: string;
  estimateId?: string;
  hire?: HireItem;
  id?: string;
  labour?: LabourItem[];
  message?: string;
  poNumber?: string;
  rejectedBy?: string;
  scaffold?: Item;
  scaffoldCode?: string;
  scaffoldId?: string;
  siteId?: string;
  siteName?: string;
  startDate?: any;
  status?: string;
  subtotal?: number;
  tax?: number;
  total?: number;
  totalOutstanding?: number;
  totalPaid?: number;
  updatedBy?: string;
  vat?: number;
  woNumber?: string;
}
