import { AdditionalItem } from './additionalItem.model';
import { Customer } from './customer.model';
import { HireItem } from './hireItem.model';
import { Item } from './item.model';
import { LabourBroker } from './labour-broker.model';
import { LabourItem } from './labourItem.model';
import { Scaffold } from './scaffold.model';
import { TransportItem, Transport } from './transport.model';

export interface Modification {
  additionals: AdditionalItem[];
  boards: Item[];
  attachments: Item[];
  broker: LabourBroker;
  code: string;
  company: { [key: string]: string };
  customer: Customer;
  date: any;
  discount: number;
  discountPercentage: number;
  endDate: any;
  hire: HireItem;
  id: string;
  labour: LabourItem[];
  transport: TransportItem[];
  transportProfile: Transport[];
  message: string;
  scaffold: Item;
  siteName: string;
  startDate: any;
  status: string;
  subtotal: number;
  tax: number;
  total: number;
  vat: number;
  poNumber: string;
  woNumber: string;
  siteId: string;
  scaffoldId: string;
  scaffoldCode: string;
  createdBy: string;
  updatedBy: string;
  acceptedBy: string;
  rejectedBy: string;
  oldScaffold?: Scaffold;
}
