import { AdditionalItem } from './additionalItem.model';
import { Handover } from './handover.model';
import { HireItem } from './hireItem.model';
import { Inspection } from './inspection.model';
import { Item } from './item.model';
import { LabourItem } from './labourItem.model';
import { TransportItem } from './transport.model';
import { User } from './user.model';

export interface Scaffold {
  id?: string;
  code?: string;
  date?: any;
  companyId?: string;
  customerId?: string;
  siteId?: string;
  siteCode?: string;
  siteName?: string;
  createdBy?: string;
  scaffold?: Item;
  attachments?: Item[];
  boards?: Item[];
  hire?: HireItem;
  labour?: LabourItem[];
  additionals?: AdditionalItem[];
  transport?: TransportItem[];
  poNumber?: string;
  woNumber?: string;
  updatedBy?: string;
  startDate?: any;
  endDate?: any;
  status?: string;
  users?: User[];
  totalInspections?: number;
  totalHandovers?: number;
  totalModifications?: number;
  totalInvoices?: number;
  totalArea?: number;
  totalPlatforms?: number;
  latestHandover?: Handover;
  latestInspection?: Inspection;
}
