/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https?://quicktype.io

export interface XeroContact {
  ContactID?: string;
  CompanyNumber?: string;
  ContactStatus?: string;
  Name?: string;
  FirstName?: string;
  LastName?: string;
  EmailAddress?: string;
  BankAccountDetails?: string;
  TaxNumber?: string;
  Addresses?: Address[];
  Phones?: Phone[];
  UpdatedDateUTC?: string;
  ContactGroups?: any[];
  IsSupplier?: boolean;
  IsCustomer?: boolean;
  Website?: string;
  BatchPayments?: BatchPayments;
  ContactPersons?: any[];
  HasAttachments?: boolean;
  HasValidationErrors?: boolean;
}

export interface Address {
  AddressType?: string;
  AddressLine1?: string;
  AddressLine2?: string;
  City?: string;
  Region?: string;
  PostalCode?: string;
  Country?: string;
}

export interface BatchPayments {
  BankAccountNumber?: string;
  BankAccountName?: string;
}

export interface Phone {
  PhoneType?: string;
  PhoneNumber?: string;
  PhoneAreaCode?: string;
  PhoneCountryCode?: string;
}
